# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ni0Xwl_i9dmHM4WKMpMMnM3c29gainuE
"""

!pip install streamlit pandas scikit-learn joblib

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
import joblib
import os

# --- 1. Load Data and Train Model (This part would typically be run once and the model saved) ---

# Check if the model and preprocessor are already saved
MODEL_PATH = 'churn_model.pkl'
PREPROCESSOR_PATH = 'preprocessor.pkl'

if not os.path.exists(MODEL_PATH) or not os.path.exists(PREPROCESSOR_PATH):
    st.write("Training model and preprocessor (this runs only once or if files are missing)...")
    # Load the dataset
    try:
        df = pd.read_csv('/content/Bank Customer Churn Prediction.csv')
    except FileNotFoundError:
        st.error("Error: 'Bank Customer Churn Prediction.csv' not found. Please ensure it's in the /content/ directory.")
        st.stop()

    # Drop irrelevant columns
    df = df.drop(columns=['CustomerId', 'Surname'])

    # Define target and features
    X = df.drop('Exited', axis=1)
    y = df['Exited']

    # Identify categorical and numerical features
    categorical_features = ['Geography', 'Gender']
    numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
    numerical_features = [f for f in numerical_features if f not in ['HasCrCard', 'IsActiveMember']]

    # Create preprocessing pipelines for numerical and categorical features
    numeric_transformer = StandardScaler()
    categorical_transformer = OneHotEncoder(handle_unknown='ignore')

    # Create a column transformer to apply different transformations to different columns
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numeric_transformer, numerical_features),
            ('cat', categorical_transformer, categorical_features)
        ],
        remainder='passthrough' # Keep other columns (like HasCrCard, IsActiveMember)
    )

    # Create a pipeline with preprocessing and a classifier
    model = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(random_state=42))
    ])

    # Split data into training and testing sets (optional for just saving the model, but good practice)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the model
    model.fit(X_train, y_train)

    # Save the trained model and preprocessor
    joblib.dump(model, MODEL_PATH)
    joblib.dump(preprocessor, PREPROCESSOR_PATH)
    st.write("Model training complete and saved.")
else:
    st.write("Loading pre-trained model and preprocessor...")
    model = joblib.load(MODEL_PATH)
    preprocessor = joblib.load(PREPROCESSOR_PATH)
    st.write("Model and preprocessor loaded.")

# --- 2. Streamlit Application Interface ---

st.set_page_config(page_title="Bank Customer Churn Prediction", layout="centered")
st.title("🏦 Bank Customer Churn Prediction")
st.markdown("This app predicts whether a bank customer will churn based on their characteristics.")

st.sidebar.header("Customer Input Features")

# Input fields for customer features
def user_input_features():
    credit_score = st.sidebar.slider('CreditScore', 350, 850, 650)
    geography = st.sidebar.selectbox('Geography', ('France', 'Germany', 'Spain'))
    gender = st.sidebar.selectbox('Gender', ('Male', 'Female'))
    age = st.sidebar.slider('Age', 18, 92, 35)
    tenure = st.sidebar.slider('Tenure (years)', 0, 10, 5)
    balance = st.sidebar.slider('Balance', 0.0, 250000.0, 50000.0)
    num_of_products = st.sidebar.slider('NumOfProducts', 1, 4, 1)
    has_cr_card = st.sidebar.selectbox('HasCrCard', (0, 1), format_func=lambda x: 'Yes' if x == 1 else 'No')
    is_active_member = st.sidebar.selectbox('IsActiveMember', (0, 1), format_func=lambda x: 'Yes' if x == 1 else 'No')
    estimated_salary = st.sidebar.slider('EstimatedSalary', 0.0, 200000.0, 100000.0)

    data = {
        'CreditScore': credit_score,
        'Geography': geography,
        'Gender': gender,
        'Age': age,
        'Tenure': tenure,
        'Balance': balance,
        'NumOfProducts': num_of_products,
        'HasCrCard': has_cr_card,
        'IsActiveMember': is_active_member,
        'EstimatedSalary': estimated_salary
    }
    features = pd.DataFrame(data, index=[0])
    return features

input_df = user_input_features()

st.subheader('User Input Features')
st.write(input_df)

# Predict button
if st.sidebar.button('Predict Churn'):
    # Make prediction
    prediction = model.predict(input_df)
    prediction_proba = model.predict_proba(input_df)

    st.subheader('Prediction Result')
    if prediction[0] == 1:
        st.error("The customer is likely to churn!")
    else:
        st.success("The customer is likely to stay.")

    st.subheader('Prediction Probability')
    st.write(f"Probability of staying: {prediction_proba[0][0]:.2f}")
    st.write(f"Probability of churning: {prediction_proba[0][1]:.2f}")

st.markdown("""
---
**Note:** If you are running this code for the first time or if the model files (`churn_model.pkl`, `preprocessor.pkl`) are not present, the model will be trained on the `Bank Customer Churn Prediction.csv` dataset. This might take a moment. Subsequent runs will load the saved model.
""")

"""### How to run this Streamlit app and deploy to GitHub:

1.  **Save the code as `app.py`**: Copy the Python code from the cell above and save it in a file named `app.py` on your local machine.

2.  **Save the dataset**: Make sure the `Bank Customer Churn Prediction.csv` file is in the same directory as `app.py`.

3.  **Install dependencies**: Create a `requirements.txt` file in the same directory with the following content:

    ```
    streamlit
    pandas
    scikit-learn
    joblib
    ```
    Then, install them using `pip install -r requirements.txt`.

4.  **Run the Streamlit app locally**: Open your terminal or command prompt, navigate to the directory where you saved `app.py`, and run:

    ```bash
    streamlit run app.py
    ```
    This will open the app in your web browser.

5.  **Initialize a Git repository**: If you don't have Git installed, install it. Then, in your project directory (where `app.py`, `requirements.txt`, and `Bank Customer Churn Prediction.csv` are located), run:

    ```bash
    git init
    git add .
    git commit -m "Initial commit: Bank Churn Prediction App"
    ```

6.  **Create a GitHub repository**: Go to [GitHub](https://github.com/), log in, and create a new repository. Do NOT initialize it with a README or license.

7.  **Link local repository to GitHub**: Copy the commands GitHub provides for linking an existing local repository. It will look something like this:

    ```bash
    git remote add origin https://github.com/yourusername/your-repo-name.git
    git branch -M main
    git push -u origin main
    ```
    Replace `yourusername` and `your-repo-name` with your actual GitHub username and repository name.

8.  **Deploy to Streamlit Cloud (Optional, Recommended)**: Once your code is on GitHub, you can easily deploy it to [Streamlit Cloud](https://streamlit.io/cloud). Connect your GitHub account, select your repository, specify `app.py` as the main file, and deploy!
"""

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
import joblib
import os

# --- 1. Load Data and Train Model (This part would typically be run once and the model saved) ---

# Check if the model and preprocessor are already saved
MODEL_PATH = 'churn_model.pkl'
PREPROCESSOR_PATH = 'preprocessor.pkl'

if not os.path.exists(MODEL_PATH) or not os.path.exists(PREPROCESSOR_PATH):
    st.write("Training model and preprocessor (this runs only once or if files are missing)...")
    # Load the dataset
    try:
        df = pd.read_csv('/content/Bank Customer Churn Prediction.csv')
    except FileNotFoundError:
        st.error("Error: 'Bank Customer Churn Prediction.csv' not found. Please ensure it's in the /content/ directory.")
        st.stop()

    # Drop irrelevant columns
    df = df.drop(columns=['CustomerId', 'Surname'])

    # Define target and features
    X = df.drop('Exited', axis=1)
    y = df['Exited']

    # Identify categorical and numerical features
    categorical_features = ['Geography', 'Gender']
    numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
    numerical_features = [f for f in numerical_features if f not in ['HasCrCard', 'IsActiveMember']]

    # Create preprocessing pipelines for numerical and categorical features
    numeric_transformer = StandardScaler()
    categorical_transformer = OneHotEncoder(handle_unknown='ignore')

    # Create a column transformer to apply different transformations to different columns
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numeric_transformer, numerical_features),
            ('cat', categorical_transformer, categorical_features)
        ],
        remainder='passthrough' # Keep other columns (like HasCrCard, IsActiveMember)
    )

    # Create a pipeline with preprocessing and a classifier
    model = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(random_state=42))
    ])

    # Split data into training and testing sets (optional for just saving the model, but good practice)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the model
    model.fit(X_train, y_train)

    # Save the trained model and preprocessor
    joblib.dump(model, MODEL_PATH)
    joblib.dump(preprocessor, PREPROCESSOR_PATH)
    st.write("Model training complete and saved.")
else:
    st.write("Loading pre-trained model and preprocessor...")
    model = joblib.load(MODEL_PATH)
    preprocessor = joblib.load(PREPROCESSOR_PATH)
    st.write("Model and preprocessor loaded.")

# --- 2. Streamlit Application Interface ---

st.set_page_config(page_title="Bank Customer Churn Prediction", layout="centered")
st.title("🏦 Bank Customer Churn Prediction")
st.markdown("This app predicts whether a bank customer will churn based on their characteristics.")

st.sidebar.header("Customer Input Features")

# Input fields for customer features
def user_input_features():
    credit_score = st.sidebar.slider('CreditScore', 350, 850, 650)
    geography = st.sidebar.selectbox('Geography', ('France', 'Germany', 'Spain'))
    gender = st.sidebar.selectbox('Gender', ('Male', 'Female'))
    age = st.sidebar.slider('Age', 18, 92, 35)
    tenure = st.sidebar.slider('Tenure (years)', 0, 10, 5)
    balance = st.sidebar.slider('Balance', 0.0, 250000.0, 50000.0)
    num_of_products = st.sidebar.slider('NumOfProducts', 1, 4, 1)
    has_cr_card = st.sidebar.selectbox('HasCrCard', (0, 1), format_func=lambda x: 'Yes' if x == 1 else 'No')
    is_active_member = st.sidebar.selectbox('IsActiveMember', (0, 1), format_func=lambda x: 'Yes' if x == 1 else 'No')
    estimated_salary = st.sidebar.slider('EstimatedSalary', 0.0, 200000.0, 100000.0)

    data = {
        'CreditScore': credit_score,
        'Geography': geography,
        'Gender': gender,
        'Age': age,
        'Tenure': tenure,
        'Balance': balance,
        'NumOfProducts': num_of_products,
        'HasCrCard': has_cr_card,
        'IsActiveMember': is_active_member,
        'EstimatedSalary': estimated_salary
    }
    features = pd.DataFrame(data, index=[0])
    return features

input_df = user_input_features()

st.subheader('User Input Features')
st.write(input_df)

# Predict button
if st.sidebar.button('Predict Churn'):
    # Make prediction
    prediction = model.predict(input_df)
    prediction_proba = model.predict_proba(input_df)

    st.subheader('Prediction Result')
    if prediction[0] == 1:
        st.error("The customer is likely to churn!")
    else:
        st.success("The customer is likely to stay.")

    st.subheader('Prediction Probability')
    st.write(f"Probability of staying: {prediction_proba[0][0]:.2f}")
    st.write(f"Probability of churning: {prediction_proba[0][1]:.2f}")

st.markdown("""
---
**Note:** If you are running this code for the first time or if the model files (`churn_model.pkl`, `preprocessor.pkl`) are not present, the model will be trained on the `Bank Customer Churn Prediction.csv` dataset. This might take a moment. Subsequent runs will load the saved model.
""")

"""### How to run this Streamlit app and deploy to GitHub:

1.  **Save the code as `app.py`**: Copy the Python code from the cell above and save it in a file named `app.py` on your local machine.

2.  **Save the dataset**: Make sure the `Bank Customer Churn Prediction.csv` file is in the same directory as `app.py`.

3.  **Install dependencies**: Create a `requirements.txt` file in the same directory with the following content:

    ```
    streamlit
    pandas
    scikit-learn
    joblib
    ```
    Then, install them using `pip install -r requirements.txt`.

4.  **Run the Streamlit app locally**: Open your terminal or command prompt, navigate to the directory where you saved `app.py`, and run:

    ```bash
    streamlit run app.py
    ```
    This will open the app in your web browser.

5.  **Initialize a Git repository**: If you don't have Git installed, install it. Then, in your project directory (where `app.py`, `requirements.txt`, and `Bank Customer Churn Prediction.csv` are located), run:

    ```bash
    git init
    git add .
    git commit -m "Initial commit: Bank Churn Prediction App"
    ```

6.  **Create a GitHub repository**: Go to [GitHub](https://github.com/), log in, and create a new repository. Do NOT initialize it with a README or license.

7.  **Link local repository to GitHub**: Copy the commands GitHub provides for linking an existing local repository. It will look something like this:

    ```bash
    git remote add origin https://github.com/yourusername/your-repo-name.git
    git branch -M main
    git push -u origin main
    ```
    Replace `yourusername` and `your-repo-name` with your actual GitHub username and repository name.

8.  **Deploy to Streamlit Cloud (Optional, Recommended)**: Once your code is on GitHub, you can easily deploy it to [Streamlit Cloud](https://streamlit.io/cloud). Connect your GitHub account, select your repository, specify `app.py` as the main file, and deploy!
"""